#!/bin/bash -x

export GO111MODULE=on 
export GOPROXY=https://goproxy.cn
# build webhook
CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o cdp-resources
# build docker image
docker build --no-cache -t daocloud.io/daocloud/cdp-resources:latest .
rm -rf cdp-resources

docker push daocloud.io/daocloud/cdp-resources:latest
