apiVersion: v1
kind: ServiceAccount
metadata:
  name: cdp-resources-sa
  labels:
    app: cdp-resources

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cdp-resources-cr
  labels:
    app: cdp-resources
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - events
  verbs:
  - "*"
- apiGroups:
  - apps
  resources:
  - deployments
  - pods
  - daemonsets
  - replicasets
  - statefulsets
  verbs:
  - "*"
- apiGroups:
  - autoscaling
  resources:
  - '*'
  verbs:
  - '*'

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cdp-resources-crb
  labels:
    app: cdp-resources
subjects:
- kind: ServiceAccount
  name: cdp-resources-sa
  namespace: jiexun-test
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cdp-resources-cr
